name: CI Test
on: [push] # 코드를 push할 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, SBS Academy!
